name: gsy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_web_browser: ^0.13.1
  flutter_cached_pdfview: ^0.3.4
  youtube_player_flutter: ^7.0.0+7
  fileaudioplayer: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/blackboard.jpg
    - assets/img/back-to-school.jpg
    - assets/img/homework.jpg
    - assets/img/back01.png
    - assets/img/back04.jpg
    - assets/img/back05.jpg
    - assets/img/zumba.jpg
    - assets/img/zumba2.jpg
    - assets/img/zumba01.jpg
    - assets/img/zumba02.jpg
    - assets/img/gsy.jpg
    - assets/img/01.jpg
    - assets/img/02.png
    - assets/img/03.png
    - assets/img/04.png
    - assets/img/05.jpg
    - assets/img/06.png    
    - assets/img/07.png
    - assets/img/08.jpg
    - assets/img/09.jpg
    - assets/img/10.png
    - assets/img/11.jpg
    - assets/img/12.png
    - assets/img/play.png
    - assets/img/pause.png
    - assets/img/stop.png
    - assets/img/next.png
    - assets/img/kulaklik.png
    - assets/img/kulaklik2.png
    - assets/img/halk_oyunu.png
    - assets/img/halk01.jpg
    - assets/img/halk02.jpg
    - assets/img/halk03.jpg
    - assets/img/halk04.jpg
    - assets/img/halk05.jpg
    - assets/img/halk06.jpg
    - assets/img/halk07.jpg
    - assets/img/gorsel01.jpg
    - assets/img/gorsel02.jpg
    - assets/img/gorsel03.jpg
    - assets/img/gorsel04.jpg
    - assets/img/gorsel05.jpg
    - assets/img/gorsel06.jpg
    - assets/img/gorsel07.jpg
    - assets/img/gorsel08.jpg
    - assets/img/gorsel09.jpg
    - assets/img/gorsel10.jpg
    - assets/img/musicPlay1.gif
    - assets/img/jandarma1.png
    - assets/img/jandarma2.jpg
    - assets/img/musicPlayer3.gif
    - assets/img/ben_cengizhan.jpg
    - assets/img/ben_dali.jpg
    - assets/img/ben_eserleri_koruyorum.jpg
    - assets/img/ben_hali.jpg
    - assets/img/ben_kitap.jpg
    - assets/img/ben_picasso.jpg
    - assets/img/ben_rodin.jpg
    - assets/img/ben_venedik_taciri.jpg
    - assets/audio/ben_cengizhan.mp3
    - assets/audio/ben_dali.mp3
    - assets/audio/ben_eserleri_koruyorum.mp3
    - assets/audio/ben_hali.mp3
    - assets/audio/ben_kitap.mp3
    - assets/audio/ben_picasso.mp3
    - assets/audio/ben_rodin.mp3
    - assets/audio/ben_venedik_taciri.mp3
    - assets/music/arkadasimEssek_BarisManco.mp3
    - assets/music/atabari.mp3
    - assets/music/biricikOgretmenim.mp3
    - assets/music/bulutOlsam.mp3
    - assets/music/canimAtaturk.mp3
    - assets/music/cilveloyNanayda.mp3
    - assets/music/cumhuriyet.mp3
    - assets/music/delilo.mp3
    - assets/music/halay2.mp3
    - assets/music/kisBaba.mp3
    - assets/music/kocekce.mp3
    - assets/music/kumestekiDostlarimiz.mp3
    - assets/music/minikSerce_sevimliTirtil.mp3
    - assets/music/mutluluguYakala.mp3
    - assets/music/orman.mp3
    - assets/music/sarkiSoylerim.mp3
    - assets/music/ucElma.mp3
    - assets/music/uskudaraGiderken.mp3
    - assets/pdf/jandarma_01.pdf
    - assets/pdf/jandarma_02.pdf
    - assets/pdf/jandarma_03.pdf
    - assets/pdf/jandarma_04.pdf
    - assets/pdf/jandarma_05.pdf
    - assets/pdf/jandarma_06.pdf
    - assets/pdf/jandarma_07.pdf
    - assets/pdf/jandarma_08.pdf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
